import type { Component } from 'vue'
import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Blocks,
  Briefcase,
  CheckCircle,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  CloudOff,
  FileText,
  Gauge,
  Globe,
  Info,
  LayoutGrid,
  Loader2,
  Lock,
  Menu,
  Moon,
  Package,
  RefreshCw,
  Shield,
  Sun,
  TrendingUp,
  University,
  XCircle,
} from 'lucide-vue-next'

export const iconRegistry: Record<string, Component> = {
  'th-large': LayoutGrid,
  'chart-line': TrendingUp,
  'shield': Shield,
  'wave-pulse': Blocks,
  'building-columns': University,
  'globe': Globe,
  'gauge': Gauge,
  'check-square': CheckSquare,
  'file': FileText,
  'box': Package,
  'lock': Lock,
  'bars': Menu,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'cloud-off': CloudOff,
  'refresh': RefreshCw,
  'spinner': Loader2,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'exclamation-triangle': AlertTriangle,
  'exclamation-circle': AlertCircle,
  'times-circle': XCircle,
  'check-circle': CheckCircle,
  'info-circle': Info,
  'briefcase': Briefcase,
  'sun': Sun,
  'moon': Moon,
}
